### ISSUE TITLE
chromium and gnome-keyring-daemon are pinning one core of my cpu at 100%

### ISSUE THREAD

**Issue by calexil** [linuxmint/gnome-keyring#2]
chromium and gnome-keyring-daemon are pinning one core of my cpu at 100%

mint 18 MATE

tried deleting default keyring and making a new one, main keyring is only about 1k...

no idea whats happening, it causes chromium to hang when closed until the daemon is killed, also spins up cpu fan like crazy

**Comment by clefebvre** [comment]
Hi,

This is Betsy's version of gnome-keyring. For Mint 18, we're using xenial's.

**Comment by calexil** [comment]
ah... so I need to report the issue to their repo?
